/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,ts}'],
  theme: {
    extend: {
      colors: {
        bg: '#FFFFFF',
        black: '#000000',
        border: '#E1E1E1',
        primary: '#223D72',
        secondary: '#D8A46F',
        shadow: '#EEF1F3',
        text: '#000000',
        third: '#46E81E',
        accent: '#D8A46F',
        sidebar: '#223D72',
        'sidebar-light': '#2A4A85',
        success: '#2E7D32',
        'success-bg': '#E8F5E9',
        'success-border': '#A5D6A7',
        error: '#C62828',
        'error-bg': '#FBE9E7',
        'error-border': '#EF9A9A',
      },
      fontFamily: {
        primary: ['Quicksand', 'system-ui', '-apple-system', 'sans-serif'],
        secondary: ['Quicksand', 'system-ui', '-apple-system', 'sans-serif'],
      },
      spacing: {
        '3xs': '4px',
        '2xs': '8px',
        xs: '12px',
        s: '16px',
        m: '24px',
        l: 'clamp(1.5rem, 1vi + 1.25rem, 2rem)',
        xl: 'clamp(2rem, 2vi + 1.5rem, 3rem)',
        '2xl': 'clamp(2.5rem, 3vi + 1.75rem, 4rem)',
        '3xl': 'clamp(3.5rem, 5vi + 2.25rem, 6rem)',
        '4xl': 'clamp(4.5rem, 7vi + 2.75rem, 8rem)',
        container: '1100px',
      },
      fontSize: {
        h1: ['23px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '0.05em' }],
        h2: ['30px', { lineHeight: '1.3', fontWeight: '700' }],
        h3: ['22px', { lineHeight: '1.3', fontWeight: '700' }],
        h4: ['18px', { lineHeight: '1.3', fontWeight: '700' }],
        'text-xl': ['clamp(1.125rem, 0.25vi + 1.06rem, 1.25rem)', { lineHeight: '1.6' }],
        'text-l': ['clamp(1rem, 0.25vi + 0.94rem, 1.125rem)', { lineHeight: '1.6' }],
        'text-m': ['16px', { lineHeight: '2', letterSpacing: '1.4px' }],
        'text-s': ['14px', { lineHeight: '1.6' }],
        'text-xs': ['12px', { lineHeight: '1.6' }],
      },
      maxWidth: {
        container: '1100px',
      },
      borderRadius: {
        DEFAULT: '12px',
        m: '16px',
      },
      boxShadow: {
        card: '0 4px 12px #EEF1F3',
        form: '0 4px 20px rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [],
};
